from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os
from datetime import datetime

class ReportGenerator:
    @staticmethod
    def generate_report(module_name, data, result, output_path):
        c = canvas.Canvas(output_path, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFont("Helvetica-Bold", 24)
        c.setFillColor(colors.darkblue)
        c.drawString(50, height - 50, "TriGen-AI Medical Report")
        
        c.setFont("Helvetica", 12)
        c.setFillColor(colors.black)
        c.drawString(50, height - 70, f"Module: {module_name}")
        c.drawString(50, height - 85, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        
        # Line
        c.setStrokeColor(colors.gray)
        c.line(50, height - 100, width - 50, height - 100)
        
        # Patient Data
        y = height - 140
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y, "Patient Data:")
        y -= 20
        c.setFont("Helvetica", 12)
        for key, value in data.items():
            if key != 'sequence': # Skip long sequence
                c.drawString(70, y, f"{key}: {value}")
                y -= 20
        
        # Line
        y -= 10
        c.setStrokeColor(colors.lightgrey)
        c.line(50, y, width - 50, y)
        y -= 30
        
        # Results
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(colors.darkblue)
        c.drawString(50, y, "AI Analysis Results:")
        y -= 25
        
        c.setFont("Helvetica", 12)
        c.setFillColor(colors.black)
        for key, value in result.items():
            if isinstance(value, list):
                c.drawString(70, y, f"{key.replace('_', ' ').title()}:")
                y -= 15
                for item in value:
                    c.drawString(90, y, f"- {item}")
                    y -= 15
            else:
                c.drawString(70, y, f"{key.replace('_', ' ').title()}: {value}")
                y -= 20
        
        # Medical Disclaimer Box
        y -= 20
        c.setStrokeColor(colors.red)
        c.setLineWidth(1)
        c.rect(50, y - 60, width - 100, 70, fill=0)
        
        c.setFont("Helvetica-Bold", 10)
        c.setFillColor(colors.red)
        c.drawString(60, y, "MEDICAL DISCLAIMER:")
        y -= 15
        c.setFont("Helvetica", 9)
        c.setFillColor(colors.black)
        disclaimer = [
            "This report is generated by an Artificial Intelligence system for educational and screening purposes only.",
            "It does NOT constitute a formal medical diagnosis, prognosis, or treatment plan.",
            "The results provided are based on the data provided and may not capture the full clinical picture.",
            "Please consult with a qualified healthcare professional (Physician/Geneticist) to interpret these results."
        ]
        for line in disclaimer:
            c.drawString(60, y, line)
            y -= 12
            
        # Footer
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(colors.gray)
        c.drawString(width/2 - 100, 30, f"TriGen-AI Patient Assessment | Reference ID: {datetime.now().strftime('%Y%m%X')}")
        
        c.save()
        return output_path
