"""Initial migration

Revision ID: 2062872e424f
Revises: 
Create Date: 2026-02-05 19:33:11.855710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2062872e424f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('context_used', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('record_date', sa.DateTime(), nullable=True),
    sa.Column('module_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('immunity_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('wbc_count', sa.Float(), nullable=True),
    sa.Column('neutrophils', sa.Float(), nullable=True),
    sa.Column('lymphocytes', sa.Float(), nullable=True),
    sa.Column('monocytes', sa.Float(), nullable=True),
    sa.Column('igg', sa.Float(), nullable=True),
    sa.Column('igm', sa.Float(), nullable=True),
    sa.Column('iga', sa.Float(), nullable=True),
    sa.Column('immunity_score', sa.Float(), nullable=True),
    sa.Column('immunity_class', sa.String(length=20), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lsd_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('beta_glucosidase', sa.Float(), nullable=True),
    sa.Column('alpha_galactosidase', sa.Float(), nullable=True),
    sa.Column('liver_size', sa.Float(), nullable=True),
    sa.Column('spleen_size', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('probability_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sickle_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('hba_percent', sa.Float(), nullable=True),
    sa.Column('hbs_percent', sa.Float(), nullable=True),
    sa.Column('hbf_percent', sa.Float(), nullable=True),
    sa.Column('hbb_sequence_snippet', sa.Text(), nullable=True),
    sa.Column('prediction', sa.String(length=20), nullable=True),
    sa.Column('genetic_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sickle_results')
    op.drop_table('lsd_results')
    op.drop_table('immunity_results')
    op.drop_table('medical_records')
    op.drop_table('chat_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
